-- Sutura — schema inicial.
-- Princípio: o dado que chega de um sistema de origem nunca é sobrescrito.
-- A identidade unificada (paciente_mestre) é uma camada por cima, ligada por vínculos
-- explícitos e auditáveis. Desfazer uma costura é apagar um vínculo, não recuperar dado.

CREATE TABLE sistema_origem (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo           VARCHAR2(20)  NOT NULL,
  nome             VARCHAR2(120) NOT NULL,
  fornecedor       VARCHAR2(120),
  unidade          VARCHAR2(120),
  protocolo        VARCHAR2(60),
  status           VARCHAR2(20)  DEFAULT 'CONECTADO' NOT NULL,
  ultima_sync      TIMESTAMP WITH TIME ZONE,
  observacao       VARCHAR2(400),
  CONSTRAINT uk_sistema_codigo UNIQUE (codigo),
  CONSTRAINT ck_sistema_status CHECK (status IN ('CONECTADO', 'ATENCAO', 'OFFLINE'))
);

COMMENT ON TABLE sistema_origem IS 'ERPs e sistemas clínicos conectados à camada Sutura';

-- O registro como ele existe no sistema de origem, sem normalizar.
-- payload_bruto guarda o documento original (FHIR/HL7) para rastreabilidade:
-- se a interpretação estiver errada, o dado de origem continua lá para reprocessar.
CREATE TABLE registro_origem (
  id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sistema_id           NUMBER        NOT NULL,
  identificador_origem VARCHAR2(80)  NOT NULL,
  nome                 VARCHAR2(200) NOT NULL,
  nome_mae             VARCHAR2(200),
  cns                  VARCHAR2(20),
  cpf                  VARCHAR2(14),
  data_nascimento      DATE,
  sexo                 VARCHAR2(1),
  payload_bruto        CLOB,
  ingerido_em          TIMESTAMP WITH TIME ZONE     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_registro_sistema FOREIGN KEY (sistema_id) REFERENCES sistema_origem (id),
  CONSTRAINT uk_registro_origem UNIQUE (sistema_id, identificador_origem)
);

CREATE INDEX ix_registro_cns ON registro_origem (cns);
CREATE INDEX ix_registro_cpf ON registro_origem (cpf);
CREATE INDEX ix_registro_nascimento ON registro_origem (data_nascimento);

COMMENT ON COLUMN registro_origem.payload_bruto IS 'Documento original recebido, preservado para auditoria e reprocessamento';

-- A identidade costurada. Não substitui os registros de origem: aponta para eles.
CREATE TABLE paciente_mestre (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_canonico   VARCHAR2(200) NOT NULL,
  cns             VARCHAR2(20),
  cpf             VARCHAR2(14),
  data_nascimento DATE,
  convenio        VARCHAR2(120),
  carteirinha     VARCHAR2(40),
  diagnostico     VARCHAR2(300),
  criado_em       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

-- A costura em si.
-- O UNIQUE em registro_origem_id é a garantia estrutural contra o prontuário falso:
-- um registro pertence a no máximo um paciente mestre. O banco recusa o erro que a
-- tela de identificação promete evitar — não depende de o serviço lembrar de checar.
CREATE TABLE vinculo_registro (
  id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_mestre_id NUMBER NOT NULL,
  registro_origem_id NUMBER NOT NULL,
  criado_em          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_vinculo_mestre   FOREIGN KEY (paciente_mestre_id) REFERENCES paciente_mestre (id),
  CONSTRAINT fk_vinculo_registro FOREIGN KEY (registro_origem_id) REFERENCES registro_origem (id),
  CONSTRAINT uk_vinculo_registro UNIQUE (registro_origem_id)
);

-- O evento pertence ao REGISTRO DE ORIGEM, nunca ao paciente mestre.
-- O vínculo com a pessoa é derivado via vinculo_registro — assim, costurar ou desfazer
-- uma costura reorganiza a linha do tempo sem tocar em nenhum evento.
CREATE TABLE evento_clinico (
  id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registro_origem_id NUMBER        NOT NULL,
  data_evento        DATE          NOT NULL,
  categoria          VARCHAR2(20)  NOT NULL,
  titulo             VARCHAR2(200) NOT NULL,
  detalhe            VARCHAR2(600),
  ciclo              VARCHAR2(40),
  CONSTRAINT fk_evento_registro FOREIGN KEY (registro_origem_id) REFERENCES registro_origem (id),
  CONSTRAINT ck_evento_categoria CHECK (categoria IN ('INFUSAO', 'CONSULTA', 'EXAME', 'CIRURGIA'))
);

CREATE INDEX ix_evento_registro ON evento_clinico (registro_origem_id);

-- Trilha de auditoria. Toda decisão de identidade fica registrada, inclusive as que
-- separam. Exigência de LGPD (dado sensível de saúde) e de qualquer auditoria clínica:
-- é preciso poder responder "quem decidiu que essas duas pessoas eram a mesma, e quando".
CREATE TABLE decisao_identificacao (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registro_a_id NUMBER        NOT NULL,
  registro_b_id NUMBER        NOT NULL,
  score         NUMBER(5, 2)  NOT NULL,
  recomendacao  VARCHAR2(20)  NOT NULL,
  decisao       VARCHAR2(20)  NOT NULL,
  usuario       VARCHAR2(80)  NOT NULL,
  justificativa VARCHAR2(400),
  decidido_em   TIMESTAMP WITH TIME ZONE     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_decisao_a FOREIGN KEY (registro_a_id) REFERENCES registro_origem (id),
  CONSTRAINT fk_decisao_b FOREIGN KEY (registro_b_id) REFERENCES registro_origem (id),
  CONSTRAINT ck_decisao_valor CHECK (decisao IN ('COSTURADO', 'SEPARADO')),
  CONSTRAINT ck_decisao_recomendacao CHECK (recomendacao IN ('COSTURAR', 'REVISAR', 'SEPARAR')),
  CONSTRAINT uk_decisao_par UNIQUE (registro_a_id, registro_b_id)
);

COMMENT ON TABLE decisao_identificacao IS 'Auditoria: quem decidiu, quando, com que score e qual recomendação o motor havia dado';
