import { Candidato, Paciente, SourceSystem, SystemId, SystemMeta } from './models';

export const SISTEMAS: Record<SystemId, SystemMeta> = {
  mv: { id: 'mv', sigla: 'MV', nome: 'MV SOUL', cor: '#2563eb' },
  tasy: { id: 'tasy', sigla: 'TASY', nome: 'Philips Tasy', cor: '#7c3aed' },
  lab: { id: 'lab', sigla: 'LAB', nome: 'Lab Alpha (LIS)', cor: '#c2410c' },
  legado: { id: 'legado', sigla: 'CSV', nome: 'SGH Legado', cor: '#64748b' },
};

export const CONEXOES: SourceSystem[] = [
  {
    id: 'mv',
    nome: 'MV SOUL',
    fornecedor: 'MV Sistemas',
    unidade: 'Hospital Santa Clara',
    protocolo: 'REST + HL7 v2',
    status: 'conectado',
    ultimaSync: 'hoje, 14:02',
    registros: 128430,
    observacao: 'Prontuário, agenda e faturamento sincronizados.',
  },
  {
    id: 'tasy',
    nome: 'Philips Tasy',
    fornecedor: 'Philips',
    unidade: 'Clínica OncoVida',
    protocolo: 'REST + FHIR R4',
    status: 'conectado',
    ultimaSync: 'hoje, 13:47',
    registros: 64108,
    observacao: 'Quimioterapia e prescrições sincronizadas.',
  },
  {
    id: 'lab',
    nome: 'Lab Alpha (LIS)',
    fornecedor: 'Alpha Diagnósticos',
    unidade: 'Rede laboratorial',
    protocolo: 'HL7 v2 (ORU)',
    status: 'conectado',
    ultimaSync: 'hoje, 13:55',
    registros: 22940,
    observacao: 'Resultados liberados em até 15 min.',
  },
  {
    id: 'legado',
    nome: 'SGH Legado',
    fornecedor: 'Interno (planilha)',
    unidade: 'Faturamento',
    protocolo: 'Importação CSV manual',
    status: 'atencao',
    ultimaSync: 'ontem, 18:20',
    registros: 4117,
    observacao: '3 linhas rejeitadas por layout fora do padrão.',
  },
];

export const CANDIDATOS: Candidato[] = [
  {
    id: 'c1',
    score: 96,
    recomendacao: 'costurar',
    justificativa: 'CNS e data de nascimento idênticos. Divergência apenas na grafia do nome.',
    ladoA: { sistema: 'mv', nome: 'MARIA APARECIDA SOUZA', identificador: 'Prontuário 448211', unidade: 'Hospital Santa Clara' },
    ladoB: { sistema: 'tasy', nome: 'M. A. SOUZA', identificador: 'Cadastro 90233', unidade: 'Clínica OncoVida' },
    campos: [
      { campo: 'CNS', a: '708 0042 8815 0003', b: '708 0042 8815 0003', situacao: 'igual' },
      { campo: 'Data de nascimento', a: '12/04/1964', b: '12/04/1964', situacao: 'igual' },
      { campo: 'Nome', a: 'MARIA APARECIDA SOUZA', b: 'M. A. SOUZA', situacao: 'divergente' },
      { campo: 'Nome da mãe', a: 'BENEDITA SOUZA', b: 'BENEDITA SOUZA', situacao: 'igual' },
      { campo: 'CPF', a: '317.485.902-11', b: '—', situacao: 'ausente' },
    ],
  },
  {
    id: 'c2',
    score: 91,
    recomendacao: 'costurar',
    justificativa: 'CNS e nome da mãe conferem. Nome difere por preposição; o CPF confirma o vínculo.',
    ladoA: { sistema: 'mv', nome: 'MARIA APARECIDA SOUZA', identificador: 'Prontuário 448211', unidade: 'Hospital Santa Clara' },
    ladoB: { sistema: 'lab', nome: 'MARIA APARECIDA DE SOUZA', identificador: 'Requisição 77120', unidade: 'Lab Alpha' },
    campos: [
      { campo: 'CNS', a: '708 0042 8815 0003', b: '708 0042 8815 0003', situacao: 'igual' },
      { campo: 'CPF', a: '317.485.902-11', b: '317.485.902-11', situacao: 'igual' },
      { campo: 'Data de nascimento', a: '12/04/1964', b: '12/04/1964', situacao: 'igual' },
      { campo: 'Nome', a: 'MARIA APARECIDA SOUZA', b: 'MARIA APARECIDA DE SOUZA', situacao: 'divergente' },
      { campo: 'Nome da mãe', a: 'BENEDITA SOUZA', b: 'BENEDITA SOUZA', situacao: 'igual' },
    ],
  },
  {
    id: 'c3',
    score: 58,
    recomendacao: 'separar',
    justificativa: 'Homônimos. CNS, CPF e data de nascimento divergem — costurar criaria um prontuário falso.',
    ladoA: { sistema: 'mv', nome: 'JOÃO CARLOS FERREIRA', identificador: 'Prontuário 210984', unidade: 'Hospital Santa Clara' },
    ladoB: { sistema: 'tasy', nome: 'JOÃO CARLOS FERREIRA', identificador: 'Cadastro 88410', unidade: 'Clínica OncoVida' },
    campos: [
      { campo: 'Nome', a: 'JOÃO CARLOS FERREIRA', b: 'JOÃO CARLOS FERREIRA', situacao: 'igual' },
      { campo: 'CNS', a: '898 0011 7742 0001', b: '702 5533 1180 0007', situacao: 'divergente' },
      { campo: 'CPF', a: '405.229.118-30', b: '981.664.207-52', situacao: 'divergente' },
      { campo: 'Data de nascimento', a: '03/09/1971', b: '28/01/1989', situacao: 'divergente' },
      { campo: 'Nome da mãe', a: 'ROSA FERREIRA', b: 'IVONE FERREIRA', situacao: 'divergente' },
    ],
  },
  {
    id: 'c4',
    score: 88,
    recomendacao: 'costurar',
    justificativa: 'CNS confere e o nome está abreviado na origem laboratorial.',
    ladoA: { sistema: 'tasy', nome: 'ANA BEATRIZ LIMA', identificador: 'Cadastro 91007', unidade: 'Clínica OncoVida' },
    ladoB: { sistema: 'lab', nome: 'ANA B. LIMA', identificador: 'Requisição 77455', unidade: 'Lab Alpha' },
    campos: [
      { campo: 'CNS', a: '706 4410 9923 0004', b: '706 4410 9923 0004', situacao: 'igual' },
      { campo: 'Data de nascimento', a: '30/11/1982', b: '30/11/1982', situacao: 'igual' },
      { campo: 'Nome', a: 'ANA BEATRIZ LIMA', b: 'ANA B. LIMA', situacao: 'divergente' },
      { campo: 'CPF', a: '228.740.615-09', b: '—', situacao: 'ausente' },
    ],
  },
  {
    id: 'c5',
    score: 73,
    recomendacao: 'revisar',
    justificativa: 'Nome e data de nascimento conferem, mas o CNS está ausente nos dois lados.',
    ladoA: { sistema: 'mv', nome: 'ROBERTO NASCIMENTO', identificador: 'Prontuário 331902', unidade: 'Hospital Santa Clara' },
    ladoB: { sistema: 'legado', nome: 'ROBERTO NASCIMENTO', identificador: 'Linha CSV 1.204', unidade: 'Faturamento' },
    campos: [
      { campo: 'Nome', a: 'ROBERTO NASCIMENTO', b: 'ROBERTO NASCIMENTO', situacao: 'igual' },
      { campo: 'Data de nascimento', a: '07/07/1958', b: '07/07/1958', situacao: 'igual' },
      { campo: 'CNS', a: '—', b: '—', situacao: 'ausente' },
      { campo: 'CPF', a: '150.883.447-20', b: '—', situacao: 'ausente' },
    ],
  },
];

export const CANDIDATOS_NOVOS: Candidato[] = [
  {
    id: 'c6',
    score: 94,
    recomendacao: 'costurar',
    justificativa: 'CNS e CPF idênticos. Nome com inversão de sobrenomes.',
    novo: true,
    ladoA: { sistema: 'mv', nome: 'CARLOS EDUARDO PRADO', identificador: 'Prontuário 452880', unidade: 'Hospital Santa Clara' },
    ladoB: { sistema: 'tasy', nome: 'CARLOS PRADO EDUARDO', identificador: 'Cadastro 91882', unidade: 'Clínica OncoVida' },
    campos: [
      { campo: 'CNS', a: '704 1188 3390 0002', b: '704 1188 3390 0002', situacao: 'igual' },
      { campo: 'CPF', a: '622.301.985-44', b: '622.301.985-44', situacao: 'igual' },
      { campo: 'Data de nascimento', a: '19/02/1977', b: '19/02/1977', situacao: 'igual' },
      { campo: 'Nome', a: 'CARLOS EDUARDO PRADO', b: 'CARLOS PRADO EDUARDO', situacao: 'divergente' },
    ],
  },
  {
    id: 'c7',
    score: 85,
    recomendacao: 'costurar',
    justificativa: 'CNS confere; o laboratório registrou apenas as iniciais.',
    novo: true,
    ladoA: { sistema: 'mv', nome: 'TEREZA CRISTINA MOURA', identificador: 'Prontuário 449017', unidade: 'Hospital Santa Clara' },
    ladoB: { sistema: 'lab', nome: 'T. C. MOURA', identificador: 'Requisição 77902', unidade: 'Lab Alpha' },
    campos: [
      { campo: 'CNS', a: '709 3320 4471 0008', b: '709 3320 4471 0008', situacao: 'igual' },
      { campo: 'Data de nascimento', a: '25/06/1969', b: '25/06/1969', situacao: 'igual' },
      { campo: 'Nome', a: 'TEREZA CRISTINA MOURA', b: 'T. C. MOURA', situacao: 'divergente' },
      { campo: 'CPF', a: '804.115.330-67', b: '—', situacao: 'ausente' },
    ],
  },
];

export const PACIENTE: Paciente = {
  id: 'p1',
  nome: 'Maria Aparecida Souza',
  nascimento: '12/04/1964',
  idade: 62,
  cns: '708 0042 8815 0003',
  cpf: '317.485.902-11',
  convenio: 'Saúde Meridiano',
  carteirinha: '0041 8827 3390 05',
  diagnostico: 'Neoplasia de mama HER2+ — protocolo de 8 ciclos',
  fontes: ['mv', 'tasy', 'lab'],
  cadastros: [
    {
      sistema: 'mv',
      nome: 'MARIA APARECIDA SOUZA',
      identificador: 'Prontuário 448211',
      cns: '708 0042 8815 0003',
      cpf: '317.485.902-11',
      unidade: 'Hospital Santa Clara',
    },
    {
      sistema: 'tasy',
      nome: 'M. A. SOUZA',
      identificador: 'Cadastro 90233',
      cns: '708 0042 8815 0003',
      cpf: '—',
      unidade: 'Clínica OncoVida',
    },
    {
      sistema: 'lab',
      nome: 'MARIA APARECIDA DE SOUZA',
      identificador: 'Requisição 77120',
      cns: '708 0042 8815 0003',
      cpf: '317.485.902-11',
      unidade: 'Lab Alpha',
    },
  ],
  eventos: [
    { id: 'e1', data: '14/08/2026', titulo: 'Infusão de Trastuzumabe 440 mg', categoria: 'infusao', sistema: 'tasy', unidade: 'Clínica OncoVida', detalhe: 'Sem intercorrências. Próximo ciclo previsto em 28 dias.', ciclo: 'Ciclo 6 de 8' },
    { id: 'e2', data: '07/08/2026', titulo: 'Hemograma completo', categoria: 'exame', sistema: 'lab', unidade: 'Lab Alpha', detalhe: 'Neutrófilos 2.100/mm³ — liberada para o próximo ciclo.' },
    { id: 'e3', data: '17/07/2026', titulo: 'Infusão de Trastuzumabe 440 mg', categoria: 'infusao', sistema: 'tasy', unidade: 'Clínica OncoVida', detalhe: 'Sem intercorrências.', ciclo: 'Ciclo 5 de 8' },
    { id: 'e4', data: '02/07/2026', titulo: 'Consulta de oncologia clínica', categoria: 'consulta', sistema: 'mv', unidade: 'Hospital Santa Clara', detalhe: 'Resposta parcial ao tratamento. Manter protocolo.' },
    { id: 'e5', data: '19/06/2026', titulo: 'Infusão de Trastuzumabe 440 mg', categoria: 'infusao', sistema: 'tasy', unidade: 'Clínica OncoVida', detalhe: 'Sem intercorrências.', ciclo: 'Ciclo 4 de 8' },
    { id: 'e6', data: '22/05/2026', titulo: 'Infusão de Trastuzumabe 440 mg', categoria: 'infusao', sistema: 'tasy', unidade: 'Clínica OncoVida', detalhe: 'Sem intercorrências.', ciclo: 'Ciclo 3 de 8' },
    { id: 'e7', data: '08/05/2026', titulo: 'Ecocardiograma', categoria: 'exame', sistema: 'mv', unidade: 'Hospital Santa Clara', detalhe: 'Fração de ejeção 62% — dentro do previsto para o protocolo.' },
    { id: 'e8', data: '24/04/2026', titulo: 'Infusão de Trastuzumabe 440 mg', categoria: 'infusao', sistema: 'tasy', unidade: 'Clínica OncoVida', detalhe: 'Sem intercorrências.', ciclo: 'Ciclo 2 de 8' },
    { id: 'e9', data: '27/03/2026', titulo: 'Infusão de Trastuzumabe 440 mg', categoria: 'infusao', sistema: 'tasy', unidade: 'Clínica OncoVida', detalhe: 'Primeira dose de ataque. Boa tolerância.', ciclo: 'Ciclo 1 de 8' },
    { id: 'e10', data: '15/03/2026', titulo: 'Mastectomia parcial', categoria: 'cirurgia', sistema: 'mv', unidade: 'Hospital Santa Clara', detalhe: 'Procedimento sem intercorrências. Alta em 48 h.' },
    { id: 'e11', data: '28/02/2026', titulo: 'Biópsia — imuno-histoquímica', categoria: 'exame', sistema: 'lab', unidade: 'Lab Alpha', detalhe: 'HER2 positivo (3+). Base da indicação do protocolo.' },
    { id: 'e12', data: '20/02/2026', titulo: 'Mamografia bilateral', categoria: 'exame', sistema: 'mv', unidade: 'Hospital Santa Clara', detalhe: 'BI-RADS 5 — encaminhada para biópsia.' },
  ],
};
